#!/bin/bash
echo -n ". $1 "
LEN=${#1}
let DOTS=20-$LEN
for i in `seq 1 $DOTS`; do SPAC=".$SPAC"; done
echo -n $SPAC

if [ -f $1/run.sh ]; then
    cd $1
    ./run.sh
    if [ $? == 0 ]; then
	echo " [OK]"
	echo "$1 $SPAC [OK]" >>../TEST.LOG
    else
	echo " [FAILED]"
	echo "$1 $SPAC [FAILED]" >>../TEST.LOG
    fi	
else
echo " [SKIPPED]"
echo "$1 $SPAC [SKIPPED]" >>../TEST.LOG
fi
