#!/bin/bash

rm -f build
if [ -d ../$1 ]; then
ln -s ../$1 build
else
echo "BUILD NOT PRESENT: $1!"
exit 0
fi

rm -f TESTED
touch TESTED

source ./tests.run

OK=`cat TESTED | grep OK | wc -l` 
FAILED=`cat TESTED | grep FAILED | wc -l` 
echo "."
echo ". TESTS PASSED: $OK  FAILED: $FAILED"
