#!/bin/bash

# ----------------------------------------------------------
# simple qscript
# ----------------------------------------------------------

# all documented in "man qsub"

# ------- name of job
#$ -N meta-np
# ------- shell to use
#$ -S /bin/bash
# ------- current working directory
#$ -cwd
# ------- environment variables (use -V to export all)
#$ -v PATH,LD_LIBRARY_PATH
# ------- email notification
# #$ -m
# #$ -M someuser@somewhere
# ------- redirect output streams 
# #$ -j            
# #$ -o logstd
# #$ -e logerr
# ------- specify ressources
# #$ -l h_rt=1:00:00     
# #$ -l h_vmem=1G        
# ------- smp job?
# #$ -l mp=1
# ------- quad node? (default: false)
# #$ -l quad=true
# ------- specific instance?
# #$ -q smp.q@quad10.beowulf.cluster
# ------- split into several tasks (SGE_TASK_ID is used then)
# #$ -t 2

# ------- SCRIPT

#  $HOME       home directory on execution machine
#  $USER       user ID of job owner
#  $JOB_ID     current job ID
#  $JOB_NAME   current job name (see -N option)
#  $HOSTNAME   name of the execution host
#  $TASK_ID    array job task index number


echo "in directory: `pwd`"
echo "on host:      `hostname`"
echo "taskid: $SGE_TASK_ID"

if [ "x$SGE_TASK_ID" == "xundefined" ]; then
RUNDIR=.
TASKDIR=.
else
RUNDIR=..
TASKDIR="task$SGE_TASK_ID"
mkdir $TASKDIR 2>/dev/null
cp scale.lua tfsfinjProfile.set $TASKDIR
cd $TASKDIR
fi

echo "* cavity reference simulation"
echo "running pre-processor"
time $RUNDIR/luacfg $RUNDIR/config-cyl-ref.lua $SGE_TASK_ID
echo "running simulation"
time $RUNDIR/meta
echo "* NP simulation"
echo "running pre-processor"
time $RUNDIR/luacfg $RUNDIR/config-cyl-np.lua  $SGE_TASK_ID
echo "running simulation"
time $RUNDIR/meta

cd $RUNDIR




